### ISSUE TITLE
implementation errors

### ISSUE THREAD

**Issue by Longseabear** [aa-samad/conv_snn#1]
hello. I am a student reproducing your paper.
I found the following problem in the code.

1. AveragePooling is removing binarization characteristics of spike input.
2. Spatial dropout is removing the binarization feature.

Actually, I can't understand that part of the paper.
"they(avgPool) do not interfere with the binary nature of the architecture (a fact never mentioned before in previous works"
Event-based spikies generally have sparse data, so of course the binary property is lost during the average pooling process (because of 0).

Also, I confirmed that a value greater than 1 occurs due to the x/(dropout weight) formula in the spatial dropout.

+) In addition, when constructing the resnet block, it was confirmed that it goes through Convolution immediately after Convolution. This is an implementation that doesn't make sense.

I want to know if there is an exact implementation code.

**Comment by aa-samad** [comment]
Hello, thank you for creating an issue,
As for the Avgpool layer, the Avgpooling layer and the next layer is assumed to be one analog layer and then the binary operator acts on them; therefore, the network flow remains binary (although we did not implement these layers separately and it appears that the network looses binary characteristics). The mentioned sentence in the paper wants to pinpoint this (which previous papers sometimes used and never explained why!).

As for the spatial dropout, well this layer is almost unnecessary, although, i did not notice any non binary outputs after the layer, i will look into this.

As for the Conv after Conv, yess that is a big mistake, there should be mem update between them! i think there was a last edit in the last minute which caused this kind of bugs. 

this code is merely the exact implementation, but if you want a better version, please be patient, i think if the world goes smoothly we will release the final code (which we used it for the journal paper) in about a week or so from this moment.

**Comment by Longseabear** [comment]
thank you! Helped a lot! Hopefully the final code will be released!
