### ISSUE TITLE
file path for record_info

### ISSUE THREAD

**Issue by arkhodamoradi** [aa-samad/conv_snn#2]
It might be better to do a pull request for this, but it is only a couple of lines..

First call to record_info will break if correct folders are not created manually. it can be fixed by adding the following lines before https://github.com/aa-samad/conv_snn/blob/master/CIFAR10-DVS/utils.py#L85

`if not os.path.exists(os.path.split(filename)[0]):
    os.makedirs(os.path.split(filename)[0])`

**Comment by aa-samad** [comment]
Thank you for creating an issue, 
Yes, correct, i will make this edit happen.
Thank you for informing this problem.
